# IMPORTANT: Move this file to the root directory of the project or adjust the Dockerfile path to run it properly
# See below for security and other concerns
# https://github.com/gstos/qbcli/blob/main/README.md#disclaimers

# No reason to define network subnet, unless you are planning to add more services
networks:
  internal:
    name: internal
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      # Adjust this for your needs; this impacts access to shared volumes
      - PUID=9999
      - PGID=9999
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    labels:
      - deunhealth.restart.on.unhealthy=true
    volumes:
      # Adjust volumes to your needs
      - ./.volumes/qb/config:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    # Required for all containers accessing the internet via this VPN service
    network_mode: service:gluetun
    healthcheck:
      # You may want to use a domain here instead of the IP address for checking DNS resolution
      test: ping -c 1 8.8.8.8 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
  gluetun:
    build:
      dockerfile: ./docker/gluetun/Dockerfile
      context: .
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # No reason to define network unless you are planning to
    networks:
      internal:
        ipv4_address: 172.39.0.2
    ports:
      # All ports from containers in `network_mode: service:gluetun` must be published here
      - "8080:8080"
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY:?missing ProtonVPN key}
      - SERVER_COUNTRIES=Netherlands
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      # You may want to comment this line in order to setup username and password in qbittorrent for the first time
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'qbcli --retry --max-retries 0 --delay 30s --timeout 5m setListeningPort {{PORTS}}'
      # Reaches out qibttorrent via host interface on the port exposed above
      - QBCLI_HOST_URL=http://127.0.0.1:8080
      - QBCLI_USERNAME=${QBCLI_USERNAME:-admin}
      - QBCLI_PASSWORD=${QBCLI_PASSWORD:?missing qbittorrent password}
      - TZ=Etc/UTC
    restart: unless-stopped
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=Etc/UTC
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Your services here...
