name: Build and Publish Docker image to GHCR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build date
        id: date
        run: echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/gluetun_qbcli
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=qbcli
            org.opencontainers.image.description=CLI tool to interact with qBittorrent WebUI
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.base.name=qmcgaw/gluetun

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/gluetun/Dockerfile
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          # TODO: pin down a version once a new one including latest PRs on Wireguard is released
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
            DATE=${{ steps.date.outputs.build_date }}
            GLUETUN_VERSION=latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
